version: 2
jobs:
  build:

    working_directory: ~

    docker:
      - image: openjdk:12-jdk

    steps:

      - checkout

      - restore_cache:
          key: core-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: core-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/core-SNAPSHOT.jar
